# Form implementation generated from reading ui file '.\templates\dlgAbout.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dlg_about(object):
    def setupUi(self, dlg_about):
        dlg_about.setObjectName("dlg_about")
        dlg_about.resize(500, 300)
        dlg_about.setMinimumSize(QtCore.QSize(500, 300))
        dlg_about.setMaximumSize(QtCore.QSize(500, 300))
        dlg_about.setModal(True)
        self.pushButton = QtWidgets.QPushButton(parent=dlg_about)
        self.pushButton.setGeometry(QtCore.QRect(170, 340, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(parent=dlg_about)
        self.label.setGeometry(QtCore.QRect(190, 110, 150, 25))
        self.label.setMinimumSize(QtCore.QSize(150, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(parent=dlg_about)
        self.label_3.setGeometry(QtCore.QRect(180, 30, 91, 51))
        self.label_3.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.label_3.setObjectName("label_3")
        self.btn_CloseAbout = QtWidgets.QPushButton(parent=dlg_about)
        self.btn_CloseAbout.setGeometry(QtCore.QRect(170, 230, 80, 25))
        self.btn_CloseAbout.setMinimumSize(QtCore.QSize(80, 25))
        self.btn_CloseAbout.setMaximumSize(QtCore.QSize(80, 25))
        self.btn_CloseAbout.setObjectName("btn_CloseAbout")
        self.label_4 = QtWidgets.QLabel(parent=dlg_about)
        self.label_4.setGeometry(QtCore.QRect(110, 180, 250, 25))
        self.label_4.setMinimumSize(QtCore.QSize(250, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setWordWrap(False)
        self.label_4.setObjectName("label_4")

        self.retranslateUi(dlg_about)
        QtCore.QMetaObject.connectSlotsByName(dlg_about)

    def retranslateUi(self, dlg_about):
        _translate = QtCore.QCoreApplication.translate
        dlg_about.setWindowTitle(_translate("dlg_about", "Dialog"))
        self.pushButton.setText(_translate("dlg_about", "PushButton"))
        self.label.setText(_translate("dlg_about", "Version 0.0.1"))
        self.label_3.setText(_translate("dlg_about", "imagen"))
        self.btn_CloseAbout.setText(_translate("dlg_about", "Close"))
        self.label_4.setText(_translate("dlg_about", "autor: Gabriel Diacich Mancilla ©"))
