# Form implementation generated from reading ui file '.\templates\dlgAbout.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dlg_about(object):
    def setupUi(self, dlg_about):
        dlg_about.setObjectName("dlg_about")
        dlg_about.resize(500, 300)
        dlg_about.setMinimumSize(QtCore.QSize(500, 300))
        dlg_about.setMaximumSize(QtCore.QSize(500, 300))
        dlg_about.setModal(True)
        self.pushButton = QtWidgets.QPushButton(parent=dlg_about)
        self.pushButton.setGeometry(QtCore.QRect(170, 340, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.widget = QtWidgets.QWidget(parent=dlg_about)
        self.widget.setGeometry(QtCore.QRect(10, 0, 481, 291))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(parent=self.widget)
        self.label_2.setMinimumSize(QtCore.QSize(150, 180))
        self.label_2.setMaximumSize(QtCore.QSize(150, 180))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(".\\templates\\assets/amiyapog.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label = QtWidgets.QLabel(parent=self.widget)
        self.label.setMinimumSize(QtCore.QSize(85, 20))
        self.label.setMaximumSize(QtCore.QSize(85, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.label_4 = QtWidgets.QLabel(parent=self.widget)
        self.label_4.setMinimumSize(QtCore.QSize(200, 20))
        self.label_4.setMaximumSize(QtCore.QSize(200, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_4.setWordWrap(False)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.btn_CloseAbout = QtWidgets.QPushButton(parent=self.widget)
        self.btn_CloseAbout.setMinimumSize(QtCore.QSize(80, 25))
        self.btn_CloseAbout.setMaximumSize(QtCore.QSize(80, 25))
        self.btn_CloseAbout.setObjectName("btn_CloseAbout")
        self.verticalLayout.addWidget(self.btn_CloseAbout, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)

        self.retranslateUi(dlg_about)
        QtCore.QMetaObject.connectSlotsByName(dlg_about)

    def retranslateUi(self, dlg_about):
        _translate = QtCore.QCoreApplication.translate
        dlg_about.setWindowTitle(_translate("dlg_about", "Dialog"))
        self.pushButton.setText(_translate("dlg_about", "PushButton"))
        self.label.setText(_translate("dlg_about", "Version 0.0.1"))
        self.label_4.setText(_translate("dlg_about", "autor: Gabriel Diacich Mancilla ©"))
        self.btn_CloseAbout.setText(_translate("dlg_about", "Close"))
